### ISSUE TITLE
scala 2.10 binaries

### ISSUE THREAD

**Issue by fommil** [chenkelmann/actuarius#7]
on Maven central, please :-D

**Comment by chenkelmann** [comment]
Hi, 
yeah you're right. A 2.10 binary is overdue. I will tackle this over the weekend, I hope to have it in maven central by Monday.

Cheers, 

Christoph

**Comment by fommil** [comment]
Cool! I'm still early enough in my project to give this a try instead of pegdown.

BTW, how easy is it to create w3c Documents (valid with XHTML1.1 headers, etc) from actuaruis? That is more important to me than a String representation.

**Comment by chenkelmann** [comment]
I just released the new 2.10.0 and 2.9.2 artifacts on maven central, so they should be available Monday morning. Would be nice if you gave actuarius a spin. I hope you'll find it useful. pegdown ist not bad either, though. 

Regarding valid xhtml creation: right now actuarius only outputs strings. The reason is that markdown allows verbatim html to be included, which in turn is not always valid xhtml. As long as you do not include any html in your input, the created string will however be well formed xhtml. You can also suppress verbatim HTML using your custom Decorator.

You can also modify the actuarius output with your own decorator. (see "Customizing the output of Actuarius" in the following wiki page https://github.com/sbt/sbt.github.com/blob/gen-master/src/jekyll/using_sonatype.md). To add your own header, you have to simply prepend it to the string output right now (admittedly not the most elegant solution)

With the current version you would have to parse the string output again if you want an XML representation where you can further manipulate the DOM.

There is however another open issue (that I have shamefully neglected) to add XHTML / XML output (or rather: completely customizable output). I will try and see if I can get this done this month.

**Comment by aggregat4** [comment]
Thanks a lot for the official 2.10 release!

Have started using Actuarius in a personal project and it's working really well so far. Easy to embed, nice docs and the Decorator approach works well for customising.
